version: '3.8'
services:

  mariadb:
    image: mariadb:10.6.2
    container_name: "user_profile_db"
    restart: always
    networks:
      - "user_profile_network"
    ports:
      - "8049:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "user_profiles"
      MYSQL_USER: "root"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+02:00']
    volumes:
      - mariadb-data:/var/lib/mysql/

  userprofilemanager:
    image: user-profile-manager:v1
    container_name: userprofilemanager
    environment:
      SERVER_PORT: "8082"
      DB_HOSTNAME: "mariadb"
      DB_PORT: "3306"
      DB_DATABASE: "user_profiles"
      DB_USER: "root"
      DB_PASS: "password"
    restart: on-failure
    networks:
      - "user_profile_network"
    ports:
      - "8083:8082"
    depends_on:
      - "mariadb"

volumes:
  mariadb-data:
    external: true

networks:
  user_profile_network:
    name: user_profile_network